Repository TeamBeMyPlan/BeMyPlan-iOS, pull requests merged in 2022-01, with the labels that each got.

#16 [feat] Home View
  BeMyPlan/BeMyPlan.xcodeproj/project.pbxproj
  BeMyPlan/BeMyPlan.xcworkspace/contents.xcworkspacedata
  BeMyPlan/BeMyPlan/Global/Extension/addSubViewFromNib.swift
  BeMyPlan/BeMyPlan/Global/Literals/ImageLiterals.swift
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/applogo.imageset/Contents.json
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/applogo.imageset/applogo.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/applogo.imageset/applogo@2x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/applogo.imageset/applogo@3x.png
  BeMyPlan/BeMyPlan/Screen/Home/Home.storyboard
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardView.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardView.xib
  BeMyPlan/BeMyPlan/Screen/Home/MainList/MainListView.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainList/MainListView.xib
  BeMyPlan/Podfile
  BeMyPlan/Podfile.lock
Labels: 🍟현주, Home

#22 Feature/15 main list view
  BeMyPlan/BeMyPlan.xcodeproj/project.pbxproj
  BeMyPlan/BeMyPlan.xcworkspace/contents.xcworkspacedata
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/maincard1.imageset/Contents.json
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/maincard1.imageset/img_main.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/maincard1.imageset/img_main@2x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/maincard1.imageset/img_main@3x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/maincard2.imageset/Contents.json
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/maincard2.imageset/Rectangle 5687.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/maincard2.imageset/Rectangle 5687@2x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/maincard2.imageset/Rectangle 5687@3x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/mainlist1.imageset/Contents.json
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/mainlist1.imageset/img.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/mainlist1.imageset/img@2x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/mainlist1.imageset/img@3x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/mainlist2.imageset/Contents.json
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/mainlist2.imageset/img.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/mainlist2.imageset/img@2x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/mainlist2.imageset/img@3x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/mainlist3.imageset/Contents.json
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/mainlist3.imageset/Rectangle 5694.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/mainlist3.imageset/Rectangle 5694@2x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/mainlist3.imageset/Rectangle 5694@3x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/mainlist4.imageset/Contents.json
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/mainlist4.imageset/Rectangle 5695.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/mainlist4.imageset/Rectangle 5695@2x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/mainlist4.imageset/Rectangle 5695@3x.png
  BeMyPlan/BeMyPlan/Screen/Home/Home.storyboard
  BeMyPlan/BeMyPlan/Screen/Home/HomeVC.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardItem/MainCardCVC.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardItem/MainCardCVC.xib
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardItem/MainCardData.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardView.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardView.xib
  BeMyPlan/BeMyPlan/Screen/Home/MainList/MainListItem/MainListCVC.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainList/MainListItem/MainListCVC.xib
  BeMyPlan/BeMyPlan/Screen/Home/MainList/MainListItem/MainListData.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainList/MainListView.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainList/MainListView.xib
Labels: 🍟현주

#31 [fix] :hammer: Panmodal Pod fixed
  BeMyPlan/Podfile
Labels: documentation, 🍔지훈

#28 [Feat] MainCardView Carousel Effect (#23)
  BeMyPlan/BeMyPlan.xcodeproj/project.pbxproj
  BeMyPlan/BeMyPlan/Global/Supporting Files/SceneDelegate.swift
  BeMyPlan/BeMyPlan/Screen/Home/Home.storyboard
  BeMyPlan/BeMyPlan/Screen/Home/HomeVC.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardCarouselLayout.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardItem/MainCardCVC.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardItem/MainCardCVC.xib
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardView.swift
Labels: 🍟현주, Home

#35 [Feat] Login View (#32)
  BeMyPlan/BeMyPlan.xcodeproj/project.pbxproj
  BeMyPlan/BeMyPlan/BeMyPlan.entitlements
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/btn_apple.imageset/Contents.json
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/btn_apple.imageset/btn_apple.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/btn_apple.imageset/btn_apple@2x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/btn_apple.imageset/btn_apple@3x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/btn_kakao.imageset/Contents.json
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/btn_kakao.imageset/btn_kakao.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/btn_kakao.imageset/btn_kakao@2x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/btn_kakao.imageset/btn_kakao@3x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/img_logo_eg.imageset/Contents.json
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/img_logo_eg.imageset/img_logo_eg.jpg
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/img_logo_eg.imageset/img_logo_eg@2x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/img_logo_eg.imageset/img_logo_eg@3x.png
  BeMyPlan/BeMyPlan/Global/Supporting Files/AppDelegate.swift
  BeMyPlan/BeMyPlan/Global/Supporting Files/SceneDelegate.swift
  BeMyPlan/BeMyPlan/Global/Utils/pressAction.swift
  BeMyPlan/BeMyPlan/Info.plist
  BeMyPlan/BeMyPlan/Screen/Login/Login.storyboard
  BeMyPlan/BeMyPlan/Screen/Login/LoginVC.swift
  BeMyPlan/BeMyPlan/Screen/Login/Social Login/LoginVC + AppleLogin.swift
  BeMyPlan/BeMyPlan/Screen/Login/Social Login/LoginVC + KakaoLogin.swift
  BeMyPlan/BeMyPlan/Screen/SignUp/SignUpNicknameVC.swift
Labels: 🍟현주, Login

#37 Feature/25 travel spot filter
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpot 2.storyboard
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpot.storyboard
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotDetailVC.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotFilterVC.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotVC 2.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotVC.swift
  BeMyPlan/Podfile.lock
Labels: enhancement, 🥯양원

#41 [feat] Login, SignUp, CustomAlert (#36)
  BeMyPlan/BeMyPlan.xcodeproj/project.pbxproj
  BeMyPlan/BeMyPlan/Global/Literals/ImageLiterals.swift
  BeMyPlan/BeMyPlan/Global/Literals/StoryboardLiterals.swift
  BeMyPlan/BeMyPlan/Global/Literals/StringLiterals.swift
  BeMyPlan/BeMyPlan/Global/Protocol/UITableViewRegisterable.swift
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/check_off_silver.imageset/Contents.json
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/check_off_silver.imageset/check_off.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/check_off_silver.imageset/check_off@2x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/check_off_silver.imageset/check_off@3x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/check_on_blue.imageset/Contents.json
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/check_on_blue.imageset/img_blue_dot.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/check_on_blue.imageset/img_blue_dot@2x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/check_on_blue.imageset/img_blue_dot@3x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/ic_back.imageset/Contents.json
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/ic_back.imageset/ic_back.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/ic_back.imageset/ic_back@2x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/ic_back.imageset/ic_back@3x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/vector.imageset/Contents.json
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/vector.imageset/Frame 35.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/vector.imageset/Frame 35@2x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/vector.imageset/Frame 35@3x.png
  BeMyPlan/BeMyPlan/Global/Supporting Files/SceneDelegate.swift
  BeMyPlan/BeMyPlan/Global/Utils/makeAlert.swift
  BeMyPlan/BeMyPlan/Global/Utils/setImage.swift
  BeMyPlan/BeMyPlan/Global/Utils/showNetworkAlert.swift
  BeMyPlan/BeMyPlan/Screen/Alert/NoTitle/CustomAlert.storyboard
  BeMyPlan/BeMyPlan/Screen/Alert/NoTitle/CustomAlertVC.swift
  BeMyPlan/BeMyPlan/Screen/Home/Home.storyboard
  BeMyPlan/BeMyPlan/Screen/Home/HomeVC.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardItem/MainCardCVC.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardView.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardView.xib
  BeMyPlan/BeMyPlan/Screen/Home/MainList/MainListItem/MainListCVC.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainList/MainListView.swift
  BeMyPlan/BeMyPlan/Screen/MyPlan/MyPlan.storyboard
  BeMyPlan/BeMyPlan/Screen/MyPlan/Setting/MyPlanSettingVC.swift
  BeMyPlan/BeMyPlan/Screen/MyPlan/WithDraw/MyPlanWithdrawVC.swift
  BeMyPlan/BeMyPlan/Screen/SignUp/SignUp.storyboard
  BeMyPlan/BeMyPlan/Screen/SignUp/SignUpNicknameVC.swift
  BeMyPlan/BeMyPlan/Screen/SignUp/SignUpVC.swift
Labels: 🍟현주

#51 [Feature] server hyunju
  BeMyPlan/BeMyPlan.xcodeproj/project.pbxproj
  BeMyPlan/BeMyPlan/Global/Model/Home/HomeData.swift
  BeMyPlan/BeMyPlan/Global/Network/BaseAPI.swift
  BeMyPlan/BeMyPlan/Global/Network/Service/HomeService.swift
  BeMyPlan/BeMyPlan/Global/Supporting Files/SceneDelegate.swift
  BeMyPlan/BeMyPlan/Screen/Home/HomeVC.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardItem/MainCardCVC.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardItem/MainCardCVC.xib
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardItem/MainCardData.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardView.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainList/MainListItem/MainListCVC.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainList/MainListItem/MainListCVC.xib
  BeMyPlan/BeMyPlan/Screen/Home/MainList/MainListView.swift
Labels: 🍟현주, Home

#53 [Feat] MainListView Data에 Params 추가....!
  BeMyPlan/BeMyPlan/Global/Model/Home/HomeData.swift
  BeMyPlan/BeMyPlan/Global/Network/BaseAPI.swift
  BeMyPlan/BeMyPlan/Global/Network/Service/HomeService.swift
  BeMyPlan/BeMyPlan/Screen/Home/HomeVC.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainList/MainListView.swift
Labels: 🍟현주, Home

#55 Feature/49 server yangwon
  BeMyPlan/BeMyPlan.xcodeproj/project.pbxproj
  BeMyPlan/BeMyPlan/Global/Model/Scrap/ScrapBtnDataModel.swift
  BeMyPlan/BeMyPlan/Global/Model/Scrap/ScrapDataModel.swift
  BeMyPlan/BeMyPlan/Global/Model/TravelSpot/TravelSpotDataModel.swift
  BeMyPlan/BeMyPlan/Global/Model/TravelSpot/TravelSpotDetail/TravelSpotDetailDataModel.swift
  BeMyPlan/BeMyPlan/Global/Network/BaseAPI.swift
  BeMyPlan/BeMyPlan/Global/Network/Service/BaseService.swift
  BeMyPlan/BeMyPlan/Global/Network/Service/ScrapBtnService.swift
  BeMyPlan/BeMyPlan/Global/Network/Service/ScrapService.swift
  BeMyPlan/BeMyPlan/Global/Network/Service/TravelSpotDetailService.swift
  BeMyPlan/BeMyPlan/Global/Network/Service/TravelSpotService.swift
  BeMyPlan/BeMyPlan/Screen/Home/HomeVC.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapVC.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapVC/ScrapContainerCVC.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapVC/ScrapContainerCVC.xib
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapVC/ScrapContainerView.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotCVC.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotDetailTVC.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotDetailTVC.xib
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotDetailVC.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotVC.swift
Labels: enhancement

#61 [feat] travelspotdetailVC 서버 4개 연결
  BeMyPlan/BeMyPlan/Global/Model/Home/HomeData.swift
  BeMyPlan/BeMyPlan/Global/Model/Scrap/ScrapDataModel.swift
  BeMyPlan/BeMyPlan/Global/Model/TravelSpot/TravelSpotDetail/TravelSpotDetailDataModel.swift
  BeMyPlan/BeMyPlan/Global/Network/BaseAPI.swift
  BeMyPlan/BeMyPlan/Global/Network/Service/HomeService.swift
  BeMyPlan/BeMyPlan/Global/Network/Service/TravelSpotDetailService.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardItem/MainCardCVC.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardView.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainList/MainListItem/MainListCVC.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainList/MainListView.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotDetailVC.swift
Labels: 🍟현주

#63 [feat] Skeleton 적용
  BeMyPlan/BeMyPlan.xcodeproj/project.pbxproj
  BeMyPlan/BeMyPlan/Global/Literals/StringLiterals.swift
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/btn_creator_upload.imageset/Contents.json
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/btn_creator_upload.imageset/btn_creator_upload.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/btn_creator_upload.imageset/btn_creator_upload@2x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/btn_creator_upload.imageset/btn_creator_upload@3x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/img_creator_guide.imageset/Contents.json
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/img_creator_guide.imageset/img_creator_guide.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/img_creator_guide.imageset/img_creator_guide@2x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/img_creator_guide.imageset/img_creator_guide@3x.png
  BeMyPlan/BeMyPlan/Global/Utils/setImage.swift
  BeMyPlan/BeMyPlan/Screen/Base/Notification/BaseVC + Notification.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardItem/MainCardCVC.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardItem/MainCardCVC.xib
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardView.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardView.xib
  BeMyPlan/BeMyPlan/Screen/Home/MainList/MainListItem/MainListCVC.xib
  BeMyPlan/BeMyPlan/Screen/Home/MainList/MainListView.swift
  BeMyPlan/BeMyPlan/Screen/MyPlan/CreatorApplication/MyPlanApplicationVC.swift
  BeMyPlan/BeMyPlan/Screen/MyPlan/MyPlan.storyboard
  BeMyPlan/BeMyPlan/Screen/MyPlan/Setting/MyPlanSettingVC.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanDetail/Cells/0-Writer/PlanDetailWriterContainerView.xib
  BeMyPlan/BeMyPlan/Screen/Plan/PlanDetail/Cells/4-Information/PlanDetailInformationTVC.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanDetail/PlanDetail.storyboard
  BeMyPlan/BeMyPlan/Screen/Plan/PlanDetail/PlanDetailVC + fetchData.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanDetail/PlanDetailVC.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/PlanPreviewVC.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotDetailVC.swift
  BeMyPlan/Podfile
  BeMyPlan/Podfile.lock
Labels: enhancement

#65 Feature/62 re paging travel spot detail
  BeMyPlan/BeMyPlan/Global/Model/Scrap/ScrapBtnDataModel.swift
  BeMyPlan/BeMyPlan/Global/Network/BaseAPI.swift
  BeMyPlan/BeMyPlan/Global/Network/Service/HomeService.swift
  BeMyPlan/BeMyPlan/Global/Network/Service/ScrapBtnService.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapEmptyVC/ScrapEmptyContainerView.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapEmptyVC/ScrapEmptyCotainerCVC.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapEmptyVC/ScrapEmptyCotainerCVC.xib
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapVC/ScrapContainerCVC.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapVC/ScrapContainerCVC.xib
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapVC/ScrapContainerView.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotCVC.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotCVC.xib
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotDetailTVC.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotDetailVC.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotVC.swift
Labels: enhancement, 🥯양원

#70 [feat] ✨ 데이터 모델 변경 - 구매, 스크랩 (#69)
  BeMyPlan/BeMyPlan/Global/Model/Home/HomeData.swift
Labels: 🍟현주

#72 [feat] indicator, plan detail 처리
  BeMyPlan/.swiftlint.yml
  BeMyPlan/BeMyPlan.xcodeproj/project.pbxproj
  BeMyPlan/BeMyPlan/Global/Literals/ImageLiterals.swift
  BeMyPlan/BeMyPlan/Global/Literals/StoryboardLiterals.swift
  BeMyPlan/BeMyPlan/Global/Model/Preview/PreviewDetailDataGettable.swift
  BeMyPlan/BeMyPlan/Global/Model/Preview/PreviewTagDataGettable.swift
  BeMyPlan/BeMyPlan/Global/Network/BaseAPI.swift
  BeMyPlan/BeMyPlan/Global/Network/Service/PlanPreviewService.swift
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/icn_mainpin_clicked.imageset/icn_mainpin_clicked.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/icn_mainpin_clicked.imageset/icn_mainpin_clicked@2x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/icn_mainpin_clicked.imageset/icn_mainpin_clicked@3x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/icn_mainpin_select.imageset/icn_mainpin_select.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/icn_mainpin_select.imageset/icn_mainpin_select@2x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/icn_mainpin_select.imageset/icn_mainpin_select@3x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/img_placeholder.imageset/Contents.json
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/img_placeholder.imageset/img_placeholder.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/img_placeholder.imageset/img_placeholder@2x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/img_placeholder.imageset/img_placeholder@3x.png
  BeMyPlan/BeMyPlan/Global/Utils/setImage.swift
  BeMyPlan/BeMyPlan/Info.plist
  BeMyPlan/BeMyPlan/Screen/Base/BaseVC.swift
  BeMyPlan/BeMyPlan/Screen/Base/Notification/BaseVC + Notification.swift
  BeMyPlan/BeMyPlan/Screen/Components/Indicator/Indicator.storyboard
  BeMyPlan/BeMyPlan/Screen/Components/Indicator/IndicatorVC.swift
  BeMyPlan/BeMyPlan/Screen/Components/Indicator/showIndicator.swift
  BeMyPlan/BeMyPlan/Screen/Home/HomeVC.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardView.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardView.xib
  BeMyPlan/BeMyPlan/Screen/Home/MainList/MainListView.swift
  BeMyPlan/BeMyPlan/Screen/Payment/Payment.storyboard
  BeMyPlan/BeMyPlan/Screen/Payment/PaymentCompleteVC.swift
  BeMyPlan/BeMyPlan/Screen/Payment/PaymentSelectVC.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanDetail/Cells/1-Map/BallonView/MapBallonView.xib
  BeMyPlan/BeMyPlan/Screen/Plan/PlanDetail/Cells/1-Map/PlanDetailMapContainerView.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanDetail/Cells/3-Summary/Cells/PlanDetailSummaryFoldTVC.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanDetail/Cells/3-Summary/Cells/PlanDetailSummaryFoldTVC.xib
  BeMyPlan/BeMyPlan/Screen/Plan/PlanDetail/Cells/3-Summary/Cells/PlanDetailSummaryRouteTVC.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanDetail/Cells/3-Summary/PlanDetailSummaryTVC.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanDetail/Cells/4-Information/PlanDetailInformationTVC.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanDetail/PlanDetailVC + fetchData.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanDetail/PlanDetailVC + setPreviewDummy.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanDetail/PlanDetailVC.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/Cells/IconContainerView/PreviewIconContainerView.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/Cells/PlanPreviewPhotoTVC.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/PlanPreview.storyboard
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/PlanPreviewVC.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotDetailVC.swift
  BeMyPlan/Podfile 3.lock
Labels: bug, documentation

#73 [feat] 무한스크롤, 리프레시 컨트롤
  BeMyPlan/BeMyPlan/Global/Model/Home/HomeData.swift
  BeMyPlan/BeMyPlan/Global/Network/BaseAPI.swift
  BeMyPlan/BeMyPlan/Global/Network/Service/BaseService.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpot.storyboard
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotCVC.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotDetailTVC.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotDetailTVC.xib
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotDetailVC.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotVC.swift
Labels: enhancement, 🥯양원

#77 [feat] EmptyView API 구현
  BeMyPlan/BeMyPlan.xcodeproj/project.pbxproj
  BeMyPlan/BeMyPlan/Global/Model/Scrap/ScrapEmptyDataModel.swift
  BeMyPlan/BeMyPlan/Global/Network/BaseAPI.swift
  BeMyPlan/BeMyPlan/Global/Network/Service/ScrapEmptyService.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainList/MainListView.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapEmptyVC/ScrapEmptyContainerView.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapEmptyVC/ScrapEmptyCotainerCVC.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapVC.swift
Labels: enhancement, 🥯양원

#75 [feat] social login server
  BeMyPlan/BeMyPlan.xcodeproj/project.pbxproj
  BeMyPlan/BeMyPlan/Global/Model/Auth/AuthDataModel.swift
  BeMyPlan/BeMyPlan/Global/Network/BaseAPI.swift
  BeMyPlan/BeMyPlan/Global/Network/Service/AuthService.swift
  BeMyPlan/BeMyPlan/Screen/Login/Social Login/LoginVC + KakaoLogin.swift
  BeMyPlan/BeMyPlan/Screen/SignUp/SignUpVC.swift
Labels: 🍟현주

#78 Feature/59 test flight helper Finish
  BeMyPlan/BeMyPlan.xcodeproj/project.pbxproj
  BeMyPlan/BeMyPlan/Global/Supporting Files/SceneDelegate.swift
  BeMyPlan/BeMyPlan/Screen/Payment/Payment.storyboard
  BeMyPlan/BeMyPlan/Screen/Payment/PaymentSelectVC.swift
  BeMyPlan/BeMyPlan/Screen/Splash/SplashVC.swift
Labels: bug, documentation

#81 Feature/76 social login sign up server
  BeMyPlan/BeMyPlan/Global/Network/BaseAPI.swift
  BeMyPlan/BeMyPlan/Global/Network/Service/AuthService.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainList/MainListView.swift
  BeMyPlan/BeMyPlan/Screen/SignUp/SignUpVC.swift
Labels: 🍟현주

#85 [feat] ✨ ListView title수정 (#84)
  BeMyPlan/BeMyPlan/Screen/Home/MainList/MainListView.swift
Labels: 🍟현주

#87 [feat] 필터뷰 버튼 수정 중
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapEmptyVC/ScrapEmptyContainerView.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapEmptyVC/ScrapEmptyCotainerCVC.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapEmptyVC/ScrapEmptyCotainerCVC.xib
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpot.storyboard
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotDetailVC.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotFilterVC.swift
Labels: enhancement, 🥯양원

#89 Feature/86 login server
  BeMyPlan/BeMyPlan/Global/Model/Auth/AuthDataModel.swift
  BeMyPlan/BeMyPlan/Global/Network/BaseAPI.swift
  BeMyPlan/BeMyPlan/Global/Network/Service/AuthService.swift
  BeMyPlan/BeMyPlan/Screen/Login/Social Login/LoginVC + KakaoLogin.swift
  BeMyPlan/BeMyPlan/Screen/SignUp/SignUpVC.swift
Labels: 🍟현주

#91 [feat] ✨ HomeDataModel id 수정 (#90)
  BeMyPlan/BeMyPlan/Global/Model/Home/HomeData.swift
Labels: 🍟현주

#93 Feature/88 filter btn
  BeMyPlan/BeMyPlan.xcodeproj/project.pbxproj
  BeMyPlan/BeMyPlan/Global/Model/Scrap/ScrapDataModel.swift
  BeMyPlan/BeMyPlan/Global/Model/TravelSpot/TravelSpotDataModel.swift
  BeMyPlan/BeMyPlan/Global/Model/TravelSpot/TravelSpotDetail/TravelSpotDetailDataModel.swift
  BeMyPlan/BeMyPlan/Global/Network/BaseAPI.swift
  BeMyPlan/BeMyPlan/Global/Network/Service/ScrapBtnService.swift
  BeMyPlan/BeMyPlan/Global/Network/Service/ScrapService.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapVC.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapVC/ScrapContainerView.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotDetailTVC.swift
Labels: enhancement, 🥯양원

#99 Feature/98 UI fix
  BeMyPlan/BeMyPlan/Global/Network/BaseAPI.swift
  BeMyPlan/BeMyPlan/Global/Network/Service/ScrapEmptyService.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapEmptyVC/ScrapEmptyContainerView.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapEmptyVC/ScrapEmptyCotainerCVC.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapVC.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapVC/ScrapContainerCVC.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapVC/ScrapContainerCVC.xib
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapVC/ScrapContainerView.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotDetailTVC.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotDetailVC.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotFilterVC.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotVC.swift
Labels: enhancement, 🥯양원

#94 Feature/92 nickname check server
  BeMyPlan/BeMyPlan.xcodeproj/project.pbxproj
  BeMyPlan/BeMyPlan/Global/Model/Auth/AuthDataModel.swift
  BeMyPlan/BeMyPlan/Global/Model/Auth/AuthNickNameDataModel.swift
  BeMyPlan/BeMyPlan/Global/Network/BaseAPI.swift
  BeMyPlan/BeMyPlan/Global/Network/Service/AuthService.swift
  BeMyPlan/BeMyPlan/Screen/SignUp/SignUp.storyboard
  BeMyPlan/BeMyPlan/Screen/SignUp/SignUpVC.swift
Labels: 🍟현주

#102 Fix/101 home loading
  BeMyPlan/BeMyPlan/Screen/Base/Base.storyboard
  BeMyPlan/BeMyPlan/Screen/Base/BaseContainerView/BaseContainerView.swift
  BeMyPlan/BeMyPlan/Screen/Base/BaseVC.swift
  BeMyPlan/DaumMap.embeddedframework/Resources/Headers 3
  BeMyPlan/DaumMap.embeddedframework/Resources/Headers 4
  BeMyPlan/DaumMap.embeddedframework/Resources/copyright 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/copyright 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/daum_copyright 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/daum_copyright 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/daum_th_line 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/daum_th_line 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/detail_button 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/detail_button 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/info_box 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/info_box 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/info_box_tail 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/info_box_tail 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_pin 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_pin 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_pin@3x 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_pin@3x 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_pin_custom 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_pin_custom 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_pin_custom@3x 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_pin_custom@3x 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_pin_red 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_pin_red 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_pin_red@3x 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_pin_red@3x 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_pin_shadow 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_pin_shadow 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_pin_shadow@3x 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_pin_shadow@3x 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_pinup 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_pinup 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_pinup@3x 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_pinup@3x 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_pinup_custom 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_pinup_custom 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_pinup_custom@3x 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_pinup_custom@3x 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_present 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_present 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_present_background_update 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_present_background_update 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_present_direction 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_present_direction 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_present_tracking 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/map_present_tracking 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/noimage 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/noimage 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/noimage256 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/noimage256 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/point_sprite 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/point_sprite 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/shadow_balloon 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/shadow_balloon 4.png
  BeMyPlan/DaumMap.embeddedframework/Resources/th_line 3.png
  BeMyPlan/DaumMap.embeddedframework/Resources/th_line 4.png
Labels: enhancement

#106 Fix/105 home skeleton
  BeMyPlan/BeMyPlan.xcodeproj/project.pbxproj
  BeMyPlan/BeMyPlan/Global/Utils/downloadImage.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardItem/MainCardCVC.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardView.swift
Labels: bug

#108 [feat] 테스트플라이트 제출용 버전 완성(2/1기준)
  BeMyPlan/.swiftlint.yml
  BeMyPlan/BeMyPlan.xcodeproj/project.pbxproj
  BeMyPlan/BeMyPlan/Coordinator/Coordinators/BaseCoordinator.swift
  BeMyPlan/BeMyPlan/Coordinator/Enums/LaunchInstructor.swift
  BeMyPlan/BeMyPlan/Coordinator/Factory/CoordinatorFactory.swift
  BeMyPlan/BeMyPlan/Coordinator/Factory/ModuleFactory.swift
  BeMyPlan/BeMyPlan/Coordinator/Protocols/BaseControllable.swift
  BeMyPlan/BeMyPlan/Coordinator/Protocols/Coordinator.swift
  BeMyPlan/BeMyPlan/Coordinator/Protocols/CoordinatorFinishOutput.swift
  BeMyPlan/BeMyPlan/Coordinator/Protocols/Presentable.swift
  BeMyPlan/BeMyPlan/Coordinator/Router/Router.swift
  BeMyPlan/BeMyPlan/Screen/Base/Base.storyboard
  BeMyPlan/BeMyPlan/Screen/Base/BaseVC.swift
  BeMyPlan/BeMyPlan/Screen/Login/LoginVC.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanDetail/Cells/0-Writer/PlanDetailWriterContainerView.xib
  BeMyPlan/BeMyPlan/Screen/Plan/PlanDetail/Cells/1-Map/PlanDetailMapContainerView.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanDetail/PlanDetail.storyboard
  BeMyPlan/BeMyPlan/Screen/Plan/PlanDetail/PlanDetailVC + fetchData.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanDetail/PlanDetailVC.swift
  BeMyPlan/BeMyPlan/Screen/Splash/SplashVC.swift
Labels: enhancement
