Repository TeamBeMyPlan/BeMyPlan-iOS, pull requests merged in 2022-03, with the labels that each got.

#119 Feature/117 app log
  BeMyPlan/BeMyPlan.xcodeproj/project.pbxproj
  BeMyPlan/BeMyPlan/Global/Manager/Analytics/AnalyticsType.swift
  BeMyPlan/BeMyPlan/Global/Manager/Analytics/AppLog.swift
  BeMyPlan/BeMyPlan/Global/Manager/Analytics/EventType/LogEventType.swift
  BeMyPlan/BeMyPlan/Global/Manager/Analytics/FirebaseServiceProtocol.swift
  BeMyPlan/BeMyPlan/Global/Manager/Analytics/Provider/FirebaseAnalyticsProvider.swift
  BeMyPlan/BeMyPlan/Global/Manager/Analytics/Provider/RuntimeProviderType.swift
  BeMyPlan/BeMyPlan/Global/Supporting Files/AppDelegate.swift
  BeMyPlan/BeMyPlan/Screen/Base/BaseVC.swift
  BeMyPlan/BeMyPlan/Screen/Base/Notification/BaseVC + Notification.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardView.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainList/MainListView.swift
  BeMyPlan/BeMyPlan/Screen/MyPlan/BuyList/MyPlanVC.swift
  BeMyPlan/BeMyPlan/Screen/MyPlan/Setting/MyPlanSettingVC.swift
  BeMyPlan/BeMyPlan/Screen/MyPlan/WithDraw/MyPlanWithdrawVC.swift
  BeMyPlan/BeMyPlan/Screen/Payment/PaymentCompleteVC.swift
  BeMyPlan/BeMyPlan/Screen/Payment/PaymentSelectVC.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanDetail/Cells/0-Writer/PlanDetailWriterContainerView.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanDetail/Cells/1-Map/PlanDetailMapContainerView.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanDetail/Cells/4-Information/PlanDetailInformationTVC.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/Cells/PlanPreviewWriterTVC.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/PlanPreviewVC.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapEmptyVC/ScrapEmptyContainerView.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapVC/ScrapContainerView.swift
  BeMyPlan/BeMyPlan/Screen/Splash/SplashVC.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotDetailVC.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotVC.swift
Labels: enhancement

#120 Feature/114 UI check
  BeMyPlan/BeMyPlan.xcodeproj/project.pbxproj
  BeMyPlan/BeMyPlan/Coordinator/Factory/ModuleFactory.swift
  BeMyPlan/BeMyPlan/Global/Literals/StringLiterals.swift
  BeMyPlan/BeMyPlan/Global/Supporting Files/SceneDelegate.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardView.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardView.xib
  BeMyPlan/BeMyPlan/Screen/Home/MainList/MainListView.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainList/MainListView.xib
  BeMyPlan/BeMyPlan/Screen/Login/LoginVC.swift
  BeMyPlan/BeMyPlan/Screen/Login/Social Login/LoginVC + KakaoLogin.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapEmptyVC/ScrapEmptyContainerView.xib
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapEmptyVC/ScrapEmptyCotainerCVC.xib
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapVC/ScrapContainerCVC.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapVC/ScrapContainerCVC.xib
  BeMyPlan/BeMyPlan/Screen/SignUp/Email/SignUpEmailVC.swift
  BeMyPlan/BeMyPlan/Screen/SignUp/NickName/SignUpNickNameVC.swift
  BeMyPlan/BeMyPlan/Screen/SignUp/SignUp.storyboard
  BeMyPlan/BeMyPlan/Screen/SignUp/SignUpVC.swift
  BeMyPlan/BeMyPlan/Screen/SignUp/TermsOfService/SignUpTOSVC.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpot.storyboard
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotDetailTVC.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotDetailTVC.xib
Labels: enhancement, 🍟현주, Home, SignUp, Login, PlanDetail

#122 [#116] SkeletonView 추가 및 사소한 UI 점검
  BeMyPlan/.swiftlint.yml
  BeMyPlan/BeMyPlan/Global/Literals/ImageLiterals.swift
  BeMyPlan/BeMyPlan/Global/Supporting Files/SceneDelegate.swift
  BeMyPlan/BeMyPlan/Global/Utils/showToastMessage.swift
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardView.xib
  BeMyPlan/BeMyPlan/Screen/MyPlan/BuyList/Cells/MyPlanBuyContentCVC.swift
  BeMyPlan/BeMyPlan/Screen/MyPlan/BuyList/MyPlanVC.swift
  BeMyPlan/BeMyPlan/Screen/MyPlan/MyPlan.storyboard
  BeMyPlan/BeMyPlan/Screen/Scrap/Scrap.storyboard
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapEmptyVC/ScrapEmptyContainerView.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapVC.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapVC/ScrapContainerCVC.xib
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapVC/ScrapContainerView.swift
  BeMyPlan/BeMyPlan/Screen/Scrap/ScrapVC/ScrapContainerView.xib
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpot.storyboard
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotCVC.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotCVC.xib
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotDetailVC.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotFilterVC.swift
  BeMyPlan/BeMyPlan/Screen/TravelSpot/TravelSpotVC.swift
Labels: bug, enhancement

#126 [feat/125] 온보딩뷰 추가
  BeMyPlan/BeMyPlan.xcodeproj/project.pbxproj
  BeMyPlan/BeMyPlan/Coordinator/Factory/ModuleFactory.swift
  BeMyPlan/BeMyPlan/Global/Literals/ImageLiterals.swift
  BeMyPlan/BeMyPlan/Global/Literals/StoryboardLiterals.swift
  BeMyPlan/BeMyPlan/Global/Literals/StringLiterals.swift
  BeMyPlan/BeMyPlan/Global/Manager/Analytics/EventType/LogEventType.swift
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/dots_1.imageset/Contents.json
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/dots_1.imageset/dots_1.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/dots_1.imageset/dots_1@2x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/dots_1.imageset/dots_1@3x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/dots_2.imageset/Contents.json
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/dots_2.imageset/dots_2.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/dots_2.imageset/dots_2@2x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/dots_2.imageset/dots_2@3x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/dots_3.imageset/Contents.json
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/dots_3.imageset/dots_3.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/dots_3.imageset/dots_3@2x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/dots_3.imageset/dots_3@3x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/img_onboarding_01.imageset/Contents.json
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/img_onboarding_01.imageset/img_onboarding_01.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/img_onboarding_01.imageset/img_onboarding_01@2x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/img_onboarding_01.imageset/img_onboarding_01@3x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/img_onboarding_02.imageset/Contents.json
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/img_onboarding_02.imageset/img_onboarding_02.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/img_onboarding_02.imageset/img_onboarding_02@2x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/img_onboarding_02.imageset/img_onboarding_02@3x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/img_onboarding_03.imageset/Contents.json
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/img_onboarding_03.imageset/img_onboarding_03.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/img_onboarding_03.imageset/img_onboarding_03@2x.png
  BeMyPlan/BeMyPlan/Global/Resource/Assets.xcassets/img_onboarding_03.imageset/img_onboarding_03@3x.png
  BeMyPlan/BeMyPlan/Global/Supporting Files/AppDelegate.swift
  BeMyPlan/BeMyPlan/Global/Supporting Files/SceneDelegate.swift
  BeMyPlan/BeMyPlan/Global/Utils/calculateTopInset.swift
  BeMyPlan/BeMyPlan/Global/Utils/pressAction.swift
  BeMyPlan/BeMyPlan/Screen/Onboarding/Onboarding.storyboard
  BeMyPlan/BeMyPlan/Screen/Onboarding/OnboardingVC + ConfigureLayout.swift
  BeMyPlan/BeMyPlan/Screen/Onboarding/OnboardingVC.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/UseCase/DefaultPlanPreviewUseCase.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/UseCase/PlanPreviewUseCase.swift
  BeMyPlan/BeMyPlan/Screen/Splash/SplashVC.swift
Labels: enhancement

#128 [Refactor/124] 구매전 미리보기 뷰에서 RxSwift + Clean Architecture로 전환 완료
  BeMyPlan/.swiftlint.yml
  BeMyPlan/BeMyPlan 2.xcworkspace/contents.xcworkspacedata
  BeMyPlan/BeMyPlan 2.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  BeMyPlan/BeMyPlan.xcodeproj/project.pbxproj
  BeMyPlan/BeMyPlan/Coordinator/Factory/ModuleFactory.swift
  BeMyPlan/BeMyPlan/Global/Model/Preview/PreviewBodyData.swift
  BeMyPlan/BeMyPlan/Global/Model/Preview/PreviewHeaderData.swift
  BeMyPlan/BeMyPlan/Global/Network/BaseAPI.swift
  BeMyPlan/BeMyPlan/Global/Network/Service/BaseService.swift
  BeMyPlan/BeMyPlan/Global/Network/Service/PlanPreviewService.swift
  BeMyPlan/BeMyPlan/Global/Protocol/ViewModelType.swift
  BeMyPlan/BeMyPlan/Global/Supporting Files/AppDelegate.swift
  BeMyPlan/BeMyPlan/Global/Supporting Files/SceneDelegate.swift
  BeMyPlan/BeMyPlan/Global/Utils/ImageSizeFetcher/ImageSizeFetcher.swift
  BeMyPlan/BeMyPlan/Global/Utils/ImageSizeFetcher/ImageSizeFetcherOperation.swift
  BeMyPlan/BeMyPlan/Global/Utils/ImageSizeFetcher/ImageSizeFetcherParser.swift
  BeMyPlan/BeMyPlan/Global/Utils/makeVibrate.swift
  BeMyPlan/BeMyPlan/Screen/Components 2/Button/BarFullButton.swift
  BeMyPlan/BeMyPlan/Screen/Components 2/Button/BarSelectButton.swift
  BeMyPlan/BeMyPlan/Screen/Components 2/ProgressBar.swift
  BeMyPlan/BeMyPlan/Screen/Components 2/ProgressBar.xib
  BeMyPlan/BeMyPlan/Screen/Home/MainCard/MainCardView.swift
  BeMyPlan/BeMyPlan/Screen/MyPlan/BuyList/MyPlanVC.swift
  BeMyPlan/BeMyPlan/Screen/Onboarding/OnboardingVC.swift
  BeMyPlan/BeMyPlan/Screen/Payment 2/Payment.storyboard
  BeMyPlan/BeMyPlan/Screen/Payment 2/PaymentCompleteVC.swift
  BeMyPlan/BeMyPlan/Screen/Payment 2/PaymentSelectVC.swift
  BeMyPlan/BeMyPlan/Screen/Payment/PaymentSelectVC.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanDetail/ViewModel/PlanDetailViewModel.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/Cells/PlanPreviewPhotoTVC.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/Cells/PlanPreviewRecommendTVC.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/Cells/PlanPreviewWriterTVC.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/PlanPreview.storyboard
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/PlanPreviewVC.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/Repository/PlanPreviewEntity.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/Repository/PlanPreviewRepository.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/UseCase/DefaultPlanPreviewUseCase.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/UseCase/Model/PreviewBodyData.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/UseCase/Model/PreviewData.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/UseCase/Model/PreviewDescriptionData.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/UseCase/Model/PreviewHeaderData.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/UseCase/Model/PreviewPhotoData.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/UseCase/Model/PreviewRecommendData.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/UseCase/Model/PreviewSummaryData.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/UseCase/PlanPreviewUseCase.swift
  BeMyPlan/BeMyPlan/Screen/Plan/PlanPreview/ViewModel/PlanPreviewViewModel.swift
  BeMyPlan/BeMyPlan/Screen/Splash/SplashVC.swift
  BeMyPlan/Podfile
  BeMyPlan/Podfile 2.lock
  BeMyPlan/Podfile.lock
Labels: bug, enhancement
